# Generated by Django 5.2.2 on 2025-06-05 19:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
